---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.1
before_install:
  - gem install bundler -v 2.0.2
  - git clone https://github.com/flutter/flutter.git
  - export PATH="$PATH:`pwd`/flutter/bin"
