---
sudo: false
language: ruby
cache: bundler
global:
  - CC_TEST_REPORTER_ID=ENV['CC_TEST_REPORTER_ID']
rvm:
  - 2.6.1
before_install:
  - gem install bundler -v 2.0.2
  - git clone https://github.com/flutter/flutter.git
  - export PATH="$PATH:`pwd`/flutter/bin"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT