title: FRap GEM
description: CLI to create a Flutter App backed with a Rails server for quick app protoyping.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
plugins:
- jekyll-seo-tag
